FROM almalinux
RUN yum install nginx -y
CMD ["nginx", "-g", "daemon off;"]
##CMD ["sleep" ,"20"] There should be only one CMD for dockerfile , if you give multiple the last one will take the preference